### ISSUE TITLE
Create a message parser

### ISSUE THREAD

**Issue by RodrigoEspinosa** [RodrigoEspinosa/gitter-cli#1]
Add a parser for the message in order to:
- [x] Show emojis.
- [x] Basic markdown parsing for bold, italic and underline text.

**Comment by RodrigoEspinosa** [comment]
## Introducing emojis 🎉

![screen shot 2015-05-17 at 8 12 35 pm](https://cloud.githubusercontent.com/assets/1685621/7672663/1b72a55e-fcd1-11e4-8b24-9227798c2a62.png)

**Comment by RodrigoEspinosa** [comment]
## Now with basic markdown parser

![screen shot 2015-05-17 at 8 13 57 pm](https://cloud.githubusercontent.com/assets/1685621/7672671/51cdb1ca-fcd1-11e4-8aa6-d7100f234ee3.png)

**Comment by juliosueiras** [comment]
Hi, sorry to bother you, just want to point out there is security issue in the program, for some reason if no token is specify(first install and first run) it will use your identity as the sender

**Comment by RodrigoEspinosa** [comment]
@juliosueiras: You're right! As I know, the token should be removed from the npm repository at this point but no for previous versions so I'd like to renew my personal Gitter token, unfortunately [there's no way to do that on Gitter yet](https://github.com/gitterHQ/gitter/issues/679), hope they add that feature soon!

Thanks for the feedback!
