### ISSUE TITLE
Fails to start: "The token is not correct" or "Error: Cannot find module 'commander'"

### ISSUE THREAD

**Issue by Flashwalker** [RodrigoEspinosa/gitter-cli#16]
When i try to start **gitter-cli 0.8.5** from **npm repo** it says:  

```
gitter-cli set-auth ******...******
The token is not correct.
```

When i try to start **gitter-cli** from **github** it says:  

```
gitter-cli
module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/deniz/gitter-cli/lib/main.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

**Comment by GitGoingBrains** [comment]
I'm getting the first outcome "token is not correct" using a digital ocean debian server.

**Comment by Flashwalker** [comment]
Suddenly I found the cause of failure.
The version installed via **npm** (`sudo npm install...`) works only via **sudo** (`sudo gitter-cli`).
Question is how to set it up to work in user space, not under root?...

**Comment by GitGoingBrains** [comment]
Yes, I also tried using sudo, and everything works....

**Comment by RodrigoEspinosa** [comment]
The best way to run this project is by installing it with `npm install --global gitter-cli` (`npm install -g gitter-cli`) is an alias. 

If you wish to run the application from the repo you need to:
1. [Download](https://github.com/RodrigoEspinosa/gitter-cli/archive/master.zip) or [fork](https://github.com/RodrigoEspinosa/gitter-cli#fork-destination-box) the repository.
2. Go to the project root directory.
3. Run `npm install` to install all dependencies.
4. Execute the application (again, from the project root directory)  with `./bin/gitter-cli`.

_Remember to check if your npm is correctly installed._

**Comment by Flashwalker** [comment]
O, Thnx, it works now!
