### ISSUE TITLE
Just do not work

### ISSUE THREAD

**Issue by iho** [RodrigoEspinosa/gitter-cli#18]
```
➜  ~ gitter-cli authorize <<HIDDEN_TOKEN>>

The token is not correct.
```

```
➜  ~ gitter-cli set-auth <<HIDDEN_TOKEN>>

The token is not correct.
```

Please help

**Comment by RodrigoEspinosa** [comment]
Hi @iho, sorry it's not working for you.

Just to confirm, you are using the token from this page?

<img width="687" alt="screen shot 2016-04-17 at 9 57 29 pm" src="https://cloud.githubusercontent.com/assets/1685621/14591415/8d295390-04e7-11e6-93b4-536e25b9ba30.png">

**Comment by iho** [comment]
@RodrigoEspinosa yes, I use token from this page https://developer.gitter.im/apps

**Comment by RodrigoEspinosa** [comment]
Given that the nature of this issue is _somehow_ related to sensitive information, as your token. Do you mind sending me a direct message over Twitter? Here is my user: [@reciam](https://twitter.com/reciam) (_direct messages are open for everyone_).

Thanks!

**Comment by NathanBland** [comment]
For others who try this, I had a similar issue... Ended up having to run that with `sudo` to set the token with `authorize`

**Comment by raspbeguy** [comment]
why does it work better as superuser ? I think it is very wrong.

**Comment by RodrigoEspinosa** [comment]
That shouldn't be the case if `node` and `npm` were installed correctly. Installing packages with the global flag (`npm install -g` or `npm install --global`) should work without _sudoing_.
