### ISSUE TITLE
WhoAmI / me commands not returning anything 

### ISSUE THREAD

**Issue by travs** [RodrigoEspinosa/gitter-cli#8]
System info:

```
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
```

Running `me` and `whoami` return nothing when I'm not logged in, when it seems they [should](https://github.com/RodrigoEspinosa/gitter-cli/blob/6de58129f0966658507af14996b6b2c81d3ac70c/lib/commands.js#L82) return `You are not logged in.`

```
$ gitter-cli me 

$ 
```

**Comment by RodrigoEspinosa** [comment]
Thanks @travs for reporting this!
